---
- name: Test Variables (Play 1)
  hosts: s1-spine1
  gather_facts: false

  tasks:

    - name: Import Global Vars
      ansible.builtin.include_vars: "{{ item }}"
      with_items:
        - "HNB_Globals.yml"
      delegate_to: localhost

    - name: Print variables
      debug:
        # msg: "{{ ntp_servers }}"
        # AVD Data Model for NTP
        msg: "{{ ntp }}"

    # - name: Generate Structured Variables per Device
    #   ansible.builtin.import_role:
    #     name: arista.avd.eos_designs

    # - name: Generate Intended Config and Documentation
    #   ansible.builtin.import_role:
    #     name: arista.avd.eos_cli_config_gen